### ISSUE TITLE
Título y datos

### ISSUE THREAD

**Issue by DrJoseGallardo** [KarlaCastroM/KarlaCastroM#2]
Estimada Karla:

Favor dar título a tu proyecto y agregar información de los datos para poder evaluar.

Saludos

**Comment by KarlaCastroM** [comment]
Estimado Jose: 
Aún no decido bien que datos voy a contemplar, por ello no he puesto título, ni información de los datos. Estoy ordenando las planillas que tengo y posteriormente comenzaré a trabajar en rstudio y github. 
Saludos 


Enviado desde mi iPhone
